version: '3.8'

services:
  # Databases & Cache
  mongodb:
    image: mongo:latest
    command: ["--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27018:27017"
    networks:
      - app-network
    restart: always

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    networks:
      - app-network
    restart: always

  kafka:
    image: apache/kafka:latest
    ports:
      - "9092:9092"
    environment:
      # KRaft settings (No Zookeeper needed)
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:29093
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_LOG_DIRS=/tmp/kraft-combined-logs
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_MESSAGE_MAX_BYTES=20000000
      - KAFKA_REPLICA_FETCH_MAX_BYTES=20000000
    networks:
      - app-network
    restart: always



  # Monitoring & Observability
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app-network
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3007:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - app-network
    restart: always

  kafka-exporter:
    image: danielqsj/kafka-exporter:latest
    container_name: kafka-exporter
    command: ["--kafka.server=kafka:29092"]
    ports:
      - "9308:9308"
    depends_on:
      - kafka
    networks:
      - app-network
    restart: always

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop
    ports:
      - "9000:9000"
    environment:
      - KAFKA_BROKERCONNECT=kafka:29092
      - JVM_OPTS=-Xms32M -Xmx64M
      - SERVER_SERVLET_CONTEXTPATH=/
    depends_on:
      - kafka
    networks:
      - app-network
    restart: always

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686" # Jaeger UI
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
    networks:
      - app-network
    restart: always



  # Microservices
  gateway:
    build:
      context: ./gateway
      target: builder
    # Use watch mode for real-time changes
    command: npm run start:dev
    environment:
      - SERVICE_NAME=gateway
    ports:
      - "3000:3000"
    volumes:
      - ./gateway/src:/usr/src/app/src
    depends_on:
      - user-wallet
      - transaction
      - payroll
      - fx
      - ledger
    networks:
      - app-network

  user-wallet:
    build:
      context: ./user-wallet
      target: builder
    command: npm run start:dev
    environment:
      - SERVICE_NAME=user-wallet
    ports:
      - "3001:3001"
    volumes:
      - ./user-wallet/src:/usr/src/app/src
    depends_on:
      - mongodb
      - kafka
    networks:
      - app-network

  transaction:
    build:
      context: ./transaction
      target: builder
    command: npm run start:dev
    environment:
      - SERVICE_NAME=transaction
    ports:
      - "3002:3002"
    volumes:
      - ./transaction/src:/usr/src/app/src
    depends_on:
      - user-wallet
      - ledger
      - fx
      - kafka
    networks:
      - app-network

  ledger:
    build:
      context: ./ledger
      target: builder
    command: npm run start:dev
    environment:
      - SERVICE_NAME=ledger
    ports:
      - "3003:3003"
    volumes:
      - ./ledger/src:/usr/src/app/src
    depends_on:
      - mongodb
    networks:
      - app-network

  fx:
    build:
      context: ./fx
      target: builder
    command: npm run start:dev
    environment:
      - SERVICE_NAME=fx
    ports:
      - "3004:3004"
    volumes:
      - ./fx/src:/usr/src/app/src
    depends_on:
      - redis
    networks:
      - app-network

  payroll:
    build:
      context: ./payroll
      target: builder
    command: npm run start:dev
    environment:
      - SERVICE_NAME=payroll
    ports:
      - "3005:3005"
    volumes:
      - ./payroll/src:/usr/src/app/src
    depends_on:
      - redis
      - transaction
    networks:
      - app-network

  admin:
    build:
      context: ./admin
      target: builder
    command: npm run start:dev
    environment:
      - SERVICE_NAME=admin
    ports:
      - "3006:3006"
    volumes:
      - ./admin/src:/usr/src/app/src
    depends_on:
      - mongodb
    networks:
      - app-network
    restart: always

  dashboard:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./dashboard:/usr/share/nginx/html
    depends_on:
      - gateway
    networks:
      - app-network
    restart: always

volumes:
  mongodb_data:
  redis_data:

networks:
  app-network:
    driver: bridge
