# monitoring/otel-collector-config.yml
receivers:
  otlp:
    protocols:
      grpc: # Receiver for traces and logs
      http: # Receiver for traces and logs

exporters:
  # TRACES: Export to Jaeger
  otlp/jaeger:
    endpoint: "jaeger:4317"
    tls:
      insecure: true

  # METRICS: Export to Prometheus
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: "novapay"

  # LOGS: Write to console (for development)
  logging:
    loglevel: debug

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp/jaeger]
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
    logs:
      receivers: [otlp]
      exporters: [logging]
